### PR TITLE
Update API in docs and fix for a triclinic test

### PR DESCRIPTION
**Pull request by hakonanes**
This PR is made in response to https://github.com/USNavalResearchLaboratory/PyEBSDIndex/pull/47.

Maintenance changes:
* Clean up docstrings already listed in the (public) API reference in the docs
* Explicitly support Python 3.11 (although I believe 0.1.2 can already run with it)
* Use "Trusted publishers" approach instead of API token to upload package to PyPI (see link in the publish.yml file)

---

I've started to test indexing on other crystal systems than cubic. So far I've only tested on Aimo Winkelmann's triclinic pattern published as part of the supplementary material to their tutorial paper from 2016 ("Which way is up?", [doi](https://doi.org/10.1016/j.matchar.2016.04.008)). To index this triclinic pattern with PyEBSDIndex via kikuchipy, I had to change the calculation of angles in the creation of the look-up table from

```python
    ang = np.round(np.arccos(np.abs(ang))*RADEG*100).astype(np.int32) # get the unique angles between the i
```

to

```python
    ang = np.round(np.arccos(ang)*RADEG*100).astype(np.int32) # get the unique angles between the input
```

Otherwise, creation of the look-up table errored. A side-effect of this change is that more angles are left in the look-up tables for the cubic case than before (the only other case I've tested). I could not find another way to solve this though. @drowenhorst-nrl, any thoughts?

The code to create the look-up table I wanted (I've added a similar test in the test suite):

```python
from itertools import product
import numpy as np
from pyebsdindex import tripletvote

# orix.vector.Miller.from_highest_indices
hkl = [1, 1, 1]
hkl_ranges = [np.arange(-i, i + 1) for i in hkl]
hkl = np.asarray(list(product(*hkl_ranges)), dtype=int)
hkl = hkl[~np.all(hkl == 0, axis=1)]  # Remove (000)
hkl = hkl[::-1]  # Make e.g. (111) first instead of (-1-1-1)

phase = tripletvote.addphase(
    spacegroup=1,
    latticeparameter=[2, 3, 4, 70, 100, 120],
    polefamilies=hkl
)
```

These are the relevant figures from the supplementary information with the crystal structure, detector-sample pattern, orientation, and pattern:

Screenshot_DynamicS_triclinic_22_39_67_085_035_015_70_-7

Tri_Example png_output

My test using kikuchipy and PyEBSDIndex with the changes in this PR:

```python
import os
from diffpy.structure import Atom, Lattice, Structure
from diffsims.crystallography import ReciprocalLatticeVector
import kikuchipy as kp
import matplotlib.pyplot as plt
import numpy as np
from orix.crystal_map import Phase, PhaseList
from orix.quaternion import Rotation
import skimage.color as skc


# Read pattern
dir_test = "/home/hakon/kode/kikuchipy_test/geometrical_simulations_all_point_groups"
s = kp.signals.EBSD(skc.rgb2gray(plt.imread(os.path.join(dir_test, "Tri_Example.png"))))

# Make detector
detector = kp.detectors.EBSDDetector(
    shape=s.axes_manager.signal_shape[::-1],
    sample_tilt=70,
    tilt=-7,
    pc=(0.35006, 0.15, 0.85),
)

# Define crystal structure
lat = Lattice(2, 3, 4, 70, 100, 120)
phase = Phase(space_group=1, structure=Structure(lattice=lat))

# Make reflector list
ref = ReciprocalLatticeVector.from_highest_hkl(phase, hkl=(1, 1, 1))

# Indexer
phase_list = PhaseList(phase)
indexer = detector.get_indexer(phase_list, ref, tSigma=2, rSigma=2)

xmap = s.hough_indexing(phase_list, indexer, verbose=2)

# Compare solution to Bruker's
rot_bruker = Rotation.from_euler([22, 39, 67], degrees=True)
rot = xmap.rotations
print(rot_bruker.angle_with(rot, degrees=True))
# Output: [85.33466643]

simulator = kp.simulations.KikuchiPatternSimulator(ref)
sim = simulator.on_detector(detector, rot)
sim.plot(pattern=s.data)
```

Output from PyEBSDIndex:

pyebsdindex_output

Output from kikuchipy:

kp_output

### CODE REVIEW

**Comment by drowenhorst-nrl** [comment]
Ah - this is a good test.  However, having issues running the example code:
```
highest_hkl = [1, 1, 1]
hkl_ranges = [np.arange(-i, i + 1) for i in hkl]
hkl = np.asarray(list(product(*hkl_ranges)), dtype=int)
hkl = indices[~np.all(hkl == 0, axis=1)]  # Remove (000)
hkl = hkl[::-1]  # Make e.g. (111) first instead of (-1-1-1) 
```
I first get an `NameError: name 'hkl' is not defined`.  If I change the `hkl --> highest_hkl` in the line that defines `hkl_ranges` I get an error on `NameError: name 'indices' is not defined`.  I think I see what you want though, I will mess around to see if I can get it to work.  

Addressing the broader issue though.  This is my understanding, in: 
``` ang = np.round(np.arccos(np.abs(ang))*RADEG*100).astype(np.int32) ```
The absolute here is representative of the inability to detect inversion symmetry in the bands.  The Radon detects the orientation of the band, but there is no "top" or "bottom" of the band, thus when taking the dot product between the two bands (in Cartesian  space ... which that line should be doing) the best it can do is 0--90°.  

I think what is happening here is a book-keeping error, and that you are tricking it into getting past the error by removing the abs ... let me do some more work on this to make sure.

**Comment by drowenhorst-nrl** [comment]
Getting closer, @hakonanes 
Given the lack of inversion symmetry, the list of reflectors you generate has redundant reflectors right? I assumed that the user would not input redundant  reflectors ... looking like a bad assumption.  

Am I missing something here about the definition of reflectors and inversion symmetry?

**Comment by hakonanes** [comment]
Thank you for trying the reflector build snippet; it's fixed now (highest_hkl -> hkl and indices -> hkl).

> Am I missing something here about the definition of reflectors and inversion symmetry?

No, I just realized that the test I added to the test suite is incorrect. The reflector list above in the example is correct, though. Most of the reflectors are unique since the triclinic crystal only has inversion symmetry. I'll push an updated test.

**Comment by hakonanes** [comment]
I've now re-added the absolute dot product, and Aimo's triclinic example above still runs fine! I believe the triclinic case is handled correctly, now.

I would like to do some more tests of the other Laue classes and multi-phase maps, but don't have time this week. If you're happy, we could merge this and release 0.2.0, and then later on release fixes if required?

**Comment by hakonanes** [comment]
If you want I can fix the failing test.

**Comment by drowenhorst-nrl** [comment]
For what it is worth, I have an update that I will merge in here where `tripletvote` will now perform a check for 0 length reflectors, and will automatically prune reflectors that are parallel/anti-parallel.  This does mean that the number of reflectors saved in the triplet lib is not necessarily the same as what the user inputs, but it is likely more user friendly.

**Comment by hakonanes** [comment]
Thanks, it works on all tests I’ve run so far. I’ll leave it up to you to make changes to this PR or merge once you’re happy.

**Pull request merged**
